/**
 * The client entry (docs/plans/web.md W1).
 *
 * `createBrowserRouter` — data mode, per docs/STACK.md §2.3. Not framework mode:
 * this app is three tabs and a palette, and framework mode's file-route
 * conventions buy nothing it needs. The route table is a module, not a
 * directory convention, because `scripts/smoke.ts` derives its page list from a
 * module today and W2 needs it to keep doing so.
 */
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { createBrowserRouter, RouterProvider } from 'react-router';

/**
 * The self-hosted webfonts, before the app's own stylesheet (docs/plans/web.md
 * W6). Generated by `pnpm font:subset`; the `url()`s inside it are relative, so
 * Vite emits every .woff2 into the content-hashed /assets/ directory that the
 * service worker's cache-first rule already covers. A copy under `public/fonts/`
 * would keep its authored name and match no rule in that worker at all.
 */
import './styles/fonts.css';
import '@/app/globals.css';
import { initAccess } from './access/client';
import { startInstallCapture } from './pwa/install';
import { startPersistence } from './pwa/persist';
import { startRestoreListener } from './pwa/restore';
import { routes } from './routes';

const container = document.getElementById('root');
if (!container) throw new Error('index.html is missing #root');

/**
 * The `?key=` exchange, **before the first render** (docs/plans/web.md W4).
 *
 * It has to run before anything can reach the API: a component that fires a
 * gated request during its first effect would send it without the credential
 * that is sitting in the URL bar. It also rewrites the address bar, and doing
 * that before the router is constructed means `createBrowserRouter` reads the
 * URL the learner is meant to be on rather than the one carrying the secret.
 *
 * Not awaited. The key is stripped and stored synchronously, before the first
 * `await` inside; what the promise carries is the server's verdict, which lands
 * a round trip later and only decides whether the credential is kept. Blocking
 * the first render on a network round trip would put a blank screen in front of
 * every learner who has a key, to answer a question none of them asked.
 */
void initAccess();

/**
 * Install and storage persistence (docs/plans/web.md W5), also before the first
 * render, and for two different reasons.
 *
 * `startInstallCapture` has to beat the event: Chromium fires
 * `beforeinstallprompt` during page load, it is not replayed, and a listener
 * mounted by a component that the learner has not navigated to yet would never
 * see it. Missing it means the install affordance never appears at all.
 *
 * `startPersistence` is the opposite shape — it deliberately does **not** ask
 * for anything here. It reads `persisted()` and then waits for the first real
 * interaction before calling `persist()`, because Chromium answers that request
 * silently and does not reconsider for the page load. Asking during the first
 * paint of a first visit turns a grant into a refusal. See `src/pwa/persist.ts`.
 */
startInstallCapture();
startPersistence();

/**
 * And the third: a restore in *another* tab replaced the database this one is
 * reading from, so this one reloads too. One line here rather than a hook in
 * every screen, because there is one of it and it has to be listening whatever
 * the learner is looking at.
 */
startRestoreListener();

/**
 * `basename` comes from the build's own base, not from a literal.
 *
 * The default build is `base: '/'`, so this is `'/'` and changes nothing. A
 * subpath build (`vite build --base=/sub/`) is a separate invocation whose
 * output is served only under that prefix, and without this the router would
 * match `/sub/` against `/`, find nothing, and render its own 404 — assets
 * loading correctly and the app still blank. `import.meta.env.BASE_URL` is
 * substituted at build time, so the two always agree.
 */
createRoot(container).render(
  <StrictMode>
    <RouterProvider router={createBrowserRouter(routes, { basename: import.meta.env.BASE_URL })} />
  </StrictMode>,
);
