// Flat config. `eslint-config-next` is gone with Next (docs/plans/web.md W1):
// it exists to lint Next's file conventions and `next/*` imports, neither of
// which this app has any more, and it pulls `next` back in as a dependency.
//
// What it was actually earning here was the typescript-eslint recommended set
// plus the two React-hooks rules, so those are declared directly.
import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

const config = [
  {
    ignores: [
      'dist/**',
      '.next/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      '.cache/**',
      // Generated by `pnpm sw` from scripts/sw.template.js, which the workspace
      // root's config lints with service-worker globals. Linting the stamped
      // copy too would report the same findings twice and go stale between
      // builds.
      'public/sw.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // `no-irregular-whitespace` fires on the ideographic spaces and full-width
    // punctuation that appear inside Chinese string literals — which this
    // codebase is full of, on purpose. Off in strings and comments, on
    // everywhere it means a typo.
    rules: {
      'no-irregular-whitespace': [
        'error',
        { skipStrings: true, skipComments: true, skipTemplates: true, skipRegExps: true },
      ],
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  {
    files: ['**/*.tsx'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
];

export default config;
